server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  # 实体类配置文件
  type-aliases-package: com.sky.entity
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt加密时使用的密钥
  admin-secret-key: fg
  # 设置jwt过期时间，单位为秒
  admin-ttl: 7200000
  #设置前端传递过来的令牌名称
  admin-token-name: token